# Generated by Django 3.2.5 on 2021-07-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title of vacancy')),
                ('description', models.TextField(verbose_name='Description of vacancy')),
                ('city', models.TextField(verbose_name='City of vacancy')),
                ('qualification', models.TextField(verbose_name='Qualification (Junior, middle...) of vacancy')),
                ('image', models.URLField(max_length=500, verbose_name='URL of vacancy image')),
                ('siteName', models.TextField(verbose_name='Site name of vacancy')),
                ('siteLink', models.URLField(max_length=500, verbose_name='URL of vacancy')),
                ('salaryFrom', models.BigIntegerField(verbose_name='Starts salary of vacancy')),
                ('salaryTo', models.BigIntegerField(verbose_name='Ends salary of vacancy')),
                ('currency', models.TextField(verbose_name='Currency of vacancy')),
                ('idHh', models.TextField(verbose_name='Id of vacancy on hh')),
            ],
        ),
    ]
