# Generated by Django 3.2.5 on 2021-07-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='city',
            field=models.TextField(blank=True, null=True, verbose_name='City of vacancy'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='currency',
            field=models.TextField(blank=True, null=True, verbose_name='Currency of vacancy'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description of vacancy'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='idHh',
            field=models.TextField(blank=True, null=True, verbose_name='Id of vacancy on hh'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL of vacancy image'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='qualification',
            field=models.TextField(blank=True, null=True, verbose_name='Qualification (Junior, middle...) of vacancy'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salaryFrom',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Starts salary of vacancy'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salaryTo',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Ends salary of vacancy'),
        ),
    ]
