# Generated by Django 3.2.5 on 2021-07-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20210707_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='companyName',
            field=models.TextField(blank=True, null=True, verbose_name='Title of vacancy'),
        ),
    ]
