# Generated by Django 3.2.5 on 2021-07-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_jobs_companyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='siteLink',
            new_name='vacLink',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='qualification',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='companyName',
            field=models.TextField(blank=True, null=True, verbose_name='Company name of vacancy'),
        ),
    ]
